name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Set environment variables
        run: |
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}  
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          echo "GITHUB_ID=${{ secrets.GITHUB_ID }}" >> $GITHUB_ENV
          echo "GITHUB_SECRET=${{ secrets.GITHUB_SECRET }}" >> $GITHUB_ENV
      - name: Build and Deploy
        run: npm run build && npm run deploy
